### ISSUE TITLE
Header nicht darstellbar wie bisher

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/Design-RRZE-Techfak2013#12]
kriege die Einstellung nicht so hin, wie die UB das bisher im Blogdienst hatte, sollte Standard-Techfak sein, aber links der Balken neben der Kopfzeile in dunkelblau statt grau (siehe auch https://web.archive.org/web/20141119041213/http://blogs.fau.de/aktuelles/)

**Comment by cassandre** [comment]
Die UB hatte ein eigenes Design, das aus irgendeinem Grund aus den Options rausgeflogen ist (FAU(dunkelblau)). Ist jetzt wieder verfügbar.
