### ISSUE TITLE
Englische Breadcrumbs

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/Design-RRZE-Techfak2013#7]
Kurze Frage,

wenn ich das Theme für die englische Seite nutzen möchte, wo kann ich denn den Text des Breadcrumbs-Menü "Sie befinden sich hier: ..." ändern? Das Theme ist als Netzwerk/Multisite-Theme installiert.

**Comment by cassandre** [comment]
Prinzipiell stellt man die Grundsprache der Website um, indem man unter Einstellungen > Allgemein die Sprache der Seite entsprechend auswählt. Das Problem stellt sich ja mit allen System-Texten (Beschriftung des Suche-Buttons, Präsentation der Suchergebnisse, Kategorienseiten etc.). 
Es kann allerdings sein, dass das Techfak2013-Theme noch nicht fertig übersetzt ist. Es wird gerade überarbeitet und sollte Ende der Woche/Anfang nächster Woche in einer neuen Version hier und auch auf der Multisite-Instanz zur Verfügung stehen. Dann mit verbesserten Optionen (eigenes Headerbild, eigenes Logo) und eben auch einer kompletten englischen Übersetzung.
